# @file
# .travis.yml - Drupal for Travis CI Integration
#
# Template provided by https://github.com/LionsAd/drupal_ti.
#
# Based for simpletest upon:
#   https://github.com/sonnym/travis-ci-drupal-module-example

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
  fast_finish: true

install:
  - cd ..
  - git clone --branch 8.0.x http://git.drupal.org/project/drupal.git
  - mv drupal_flysystem drupal/modules/flysystem
  - cd drupal

script:
  - cd core

  - travis_retry composer require league/flysystem ^1.0.3 --prefer-source
  - travis_retry composer require league/flysystem-cached-adapter ~1.0 --prefer-source
  - travis_retry composer require league/flysystem-memory ~1.0 --prefer-source
  - travis_retry composer require league/flysystem-replicate-adapter ~1.0 --prefer-source
  - travis_retry composer require twistor/flysystem-stream-wrapper ^1.0.5 --prefer-source

  - cd ../modules/flysystem
  - ../../core/vendor/bin/phpunit

notifications:
  email: false
