# @file
# .travis.yml - Drupal for Travis CI Integration
#
# Template provided by https://github.com/LionsAd/drupal_ti.
#
# Based for simpletest upon:
#   https://github.com/sonnym/travis-ci-drupal-module-example

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

env:
  global:
    # add composer's global bin directory to the path
    # see: https://github.com/drush-ops/drush#install---composer
    - PATH="$PATH:$HOME/.composer/vendor/bin"

# mysql:
#   database: drupal
#   username: root
#   encoding: utf8

before_install:
  - composer self-update

install:
  - composer global require drush/drush:dev-master
  - phpenv rehash
  - cd ..
  - git clone --branch 8.0.x http://git.drupal.org/project/drupal.git
  - mv drupal_flysystem drupal/modules/flysystem
  - cd drupal
  # - drush --verbose site-install --db-url=mysql://root:@127.0.0.1/drupal --yes
  - drush dl composer_manager --destination=modules --dev
  # - drush en flysystem simpletest -y

script:
  - php modules/composer_manager/scripts/init.sh
  - cd core
  - composer drupal-rebuild
  - composer update --prefer-source
  - cd ../modules/flysystem
  - ../../core/vendor/bin/phpunit

after_script:

notifications:
  email: false
